env:
  NUKE_TELEMETRY_OPTOUT: 1
name: continuous

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  continuous:
    name: Run
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        BaseImage: [windows-latest]
        Configuration: [Release]
        Arch: [x86, x64]

    steps:
    - uses: actions/checkout@v3

    - name: Install Windows SDK 
      uses: ChristopheLav/windows-sdk-install@v1.0.1
      with:
        version-sdk: 19041
        features: 'OptionId.UWPCPP,OptionId.DesktopCPPx86,OptionId.DesktopCPPx64'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.Configuration}} /p:Platform=${{matrix.Arch}} .

    - name: Copy x64 Artifacts
      run: |
        mkdir final
        copy D:\a\socksme\socksme\Builds\${{matrix.Configuration}}\ntfstool*.exe final
    - uses: actions/upload-artifact@v1
      with:
        name: build-${{matrix.Configuration}}-${{matrix.Arch}}
        path: final
